local item_sounds = require("__base__.prototypes.item_sounds")

data:extend({
    {
        type = "item",
        name = "insulated-copper-cable",
        icon = "__helios__/graphics/icons/mipped/electronic/part-insulated-cable-1.png",
        icon_size = 64,
        inventory_move_sound = item_sounds.wire_inventory_move,
        pick_sound = item_sounds.wire_inventory_pickup,
        drop_sound = item_sounds.wire_inventory_move,
        subgroup = "helios-electronics",
        order = "e[electronic]-i[insulated-cable]",
        stack_size = 200,
        weight = 500,
    },
    {
        type = "item",
        name = "resistor",
        icon = "__helios__/graphics/icons/mipped/electronic/part-electronic-resistor-1.png",
        icon_size = 64,
        inventory_move_sound = item_sounds.wire_inventory_move,
        pick_sound = item_sounds.wire_inventory_pickup,
        drop_sound = item_sounds.wire_inventory_move,
        subgroup = "intermediate-product",
        order = "e[electronic]-r[resistor]",
        stack_size = 100,
        weight = 1000,
    },
    {
        type = "item",
        name = "capacitor",
        icon = "__helios__/graphics/icons/mipped/electronic/part-electronic-capacitor-1.png",
        icon_size = 64,
        inventory_move_sound = item_sounds.wire_inventory_move,
        pick_sound = item_sounds.wire_inventory_pickup,
        drop_sound = item_sounds.wire_inventory_move,
        subgroup = "intermediate-product",
        order = "e[electronic]-i[insulated-cable]",
        stack_size = 100,
        weight = 1000,
    },
    {
        type = "item",
        name = "simple-microchip",
        icon = "__helios__/graphics/icons/mipped/electronic/part-electronic-microchip-1.png",
        icon_size = 64,
        inventory_move_sound = item_sounds.electric_small_inventory_move,
        pick_sound = item_sounds.electric_small_inventory_pickup,
        drop_sound = item_sounds.electric_small_inventory_move,
        subgroup = "intermediate-product",
        order = "e[circuits]-z[microchip1]",
        stack_size = 50,
        weight = 4000,
    },
    {
        type = "item",
        name = "advanced-microchip",
        icon = "__helios__/graphics/icons/mipped/electronic/part-electronic-microchip-2.png",
        icon_size = 64,
        inventory_move_sound = item_sounds.electric_small_inventory_move,
        pick_sound = item_sounds.electric_small_inventory_pickup,
        drop_sound = item_sounds.electric_small_inventory_move,
        subgroup = "intermediate-product",
        order = "e[circuits]-z[microchip2]",
        stack_size = 50,
        weight = 4000,
    },
    {
        type = "item",
        name = "simple-printed-circuit-board",
        icon = "__helios__/graphics/icons/mipped/electronic/part-electronic-circuit-substrate-1.png",
        icon_size = 64,
        inventory_move_sound = item_sounds.electric_small_inventory_move,
        pick_sound = item_sounds.electric_small_inventory_pickup,
        drop_sound = item_sounds.electric_small_inventory_move,
        subgroup = "intermediate-product",
        order = "e[circuits]-p[pcb1]",
        stack_size = 100,
        weight = 1000,
    },
})
