local item_sounds = require("__base__.prototypes.item_sounds")

data:extend({
    {
        type = "item",
        name = "scaffolding",
        subgroup = "intermediate-product",
        order = "a[basic-intermediates]-c[basic-frame]",
        inventory_move_sound = item_sounds.metal_small_inventory_move,
        pick_sound = item_sounds.metal_small_inventory_pickup,
        drop_sound = item_sounds.metal_small_inventory_move,
        icon = "__helios__/graphics/icons/items/part-metal-scaffolding.png",
        icon_size = 64,
        stack_size = 100,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "rivet",
        subgroup = "intermediate-product",
        order = "a[basic-intermediates]-c[rivet]",
        inventory_move_sound = item_sounds.metal_small_inventory_move,
        pick_sound = item_sounds.metal_small_inventory_pickup,
        drop_sound = item_sounds.metal_small_inventory_move,
        icon = "__helios__/graphics/icons/items/part-rivets-1.png",
        icon_size = 64,
        pictures = {
            { size = 64, filename = "__helios__/graphics/icons/items/part-rivets-1.png", },
            { size = 64, filename = "__helios__/graphics/icons/items/part-rivets-2.png", },
            { size = 64, filename = "__helios__/graphics/icons/items/part-rivets-3.png", },
        },
        stack_size = 100,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "ball-bearing",
        subgroup = "intermediate-product",
        order = "a[basic-intermediates]-c[ball-bearing]",
        inventory_move_sound = item_sounds.metal_small_inventory_move,
        pick_sound = item_sounds.metal_small_inventory_pickup,
        drop_sound = item_sounds.metal_small_inventory_move,
        icon = "__helios__/graphics/icons/items/part-metal-steel-bearing.png",
        icon_size = 64,
        stack_size = 100,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "rubber-tubing",
        subgroup = "intermediate-product",
        order = "a[basic-intermediates]-c[rubber-tube]",
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        icon = "__helios__/graphics/icons/items/part-rubber-tube.png",
        icon_size = 64,
        stack_size = 100,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "rubber-gasket",
        subgroup = "intermediate-product",
        order = "a[basic-intermediates]-c[rubber-gasket]",
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        icon = "__helios__/graphics/icons/items/part-rubber-gasket-1.png",
        icon_size = 64,
        pictures = {
            { size = 64, filename = "__helios__/graphics/icons/items/part-rubber-gasket-1.png", },
            { size = 64, filename = "__helios__/graphics/icons/items/part-rubber-gasket-2.png", },
        },
        stack_size = 100,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "spring",
        subgroup = "intermediate-product",
        order = "a[basic-intermediates]-c[spring]",
        inventory_move_sound = item_sounds.metal_small_inventory_move,
        pick_sound = item_sounds.metal_small_inventory_pickup,
        drop_sound = item_sounds.metal_small_inventory_move,
        icon = "__helios__/graphics/icons/items/part-metal-spring-1.png",
        icon_size = 64,
        stack_size = 100,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "cladding",
        subgroup = "intermediate-product",
        order = "a[basic-intermediates]-c[cladding]",
        inventory_move_sound = item_sounds.metal_small_inventory_move,
        pick_sound = item_sounds.metal_small_inventory_pickup,
        drop_sound = item_sounds.metal_small_inventory_move,
        icon = "__helios__/graphics/icons/items/part-heavy-cladding.png",
        icon_size = 64,
        stack_size = 100,
        weight = 2 * kg,
    },
})
