local item_sounds = require("__base__.prototypes.item_sounds")

data:extend({
    {
        type = "item",
        name = "crushed-tin",
        icon = "__helios__/graphics/icons/items/tin/tin-crushed-1.png",
        icon_size = 64,
        pictures = {
            { size = 64, filename = "__helios__/graphics/icons/items/tin/tin-crushed-1.png", scale = 0.66 },
            { size = 64, filename = "__helios__/graphics/icons/items/tin/tin-crushed-2.png", scale = 0.66 },
            { size = 64, filename = "__helios__/graphics/icons/items/tin/tin-crushed-3.png", scale = 0.66 },
        },
        stack_size = 20,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "processed-tin",
        icon = "__helios__/graphics/icons/items/tin/tin-processed.png",
        icon_size = 32,
        stack_size = 20,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "tin-slurry",
        icon = "__helios__/graphics/icons/items/tin/tin-slurry.png",
        icon_size = 32,
        stack_size = 20,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "tin-plate",
        subgroup = "raw-material",
        order = "a[smelting]-a[tin-plate]",
        inventory_move_sound = item_sounds.metal_small_inventory_move,
        pick_sound = item_sounds.metal_small_inventory_pickup,
        drop_sound = item_sounds.metal_small_inventory_move,
        icon = "__helios__/graphics/icons/items/tin/tin-plate.png",
        icon_size = 32,
        stack_size = 100,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "tin-gear-wheel",
        subgroup = "intermediate-product",
        order = "a[basic-intermediates]-a[tin-gear-wheel]",
        inventory_move_sound = item_sounds.metal_small_inventory_move,
        pick_sound = item_sounds.metal_small_inventory_pickup,
        drop_sound = item_sounds.metal_small_inventory_move,
        icon = "__helios__/graphics/icons/items/part-metal-tin-gear-1.png",
        icon_size = 64,
        stack_size = 100,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "gear-wheel-assembly",
        subgroup = "intermediate-product",
        order = "a[basic-intermediates]-b[gear-wheel-assembly]",
        inventory_move_sound = item_sounds.metal_small_inventory_move,
        pick_sound = item_sounds.metal_small_inventory_pickup,
        drop_sound = item_sounds.metal_small_inventory_move,
        icon = "__helios__/graphics/icons/items/part-metal-gear-assembly.png",
        icon_size = 64,
        stack_size = 100,
        weight = 2 * kg,
    },
})
