data:extend({
    {
        type = "item",
        name = "crushed-tin",
        icon = "__helios__/graphics/icons/items/tin/tin-crushed-1.png",
        icon_size = 64,
        pictures = {
            { size = 64, filename = "__helios__/graphics/icons/items/tin/tin-crushed-1.png", scale = 0.66 },
            { size = 64, filename = "__helios__/graphics/icons/items/tin/tin-crushed-2.png", scale = 0.66 },
            { size = 64, filename = "__helios__/graphics/icons/items/tin/tin-crushed-3.png", scale = 0.66 },
        },
        stack_size = 20,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "processed-tin",
        icon = "__helios__/graphics/icons/items/tin/tin-processed.png",
        icon_size = 32,
        stack_size = 20,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "tin-slurry",
        icon = "__helios__/graphics/icons/items/tin/tin-slurry.png",
        icon_size = 32,
        stack_size = 20,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "tin-plate",
        icon = "__helios__/graphics/icons/items/tin/tin-plate.png",
        icon_size = 32,
        stack_size = 100,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "tin-gear-wheel",
        icon = "__helios__/graphics/icons/items/part-metal-tin-gear-1.png",
        icon_size = 64,
        stack_size = 100,
        weight = 2 * kg,
    },
    {
        type = "item",
        name = "gear-wheel-assembly",
        icon = "__helios__/graphics/icons/items/part-metal-gear-assembly.png",
        icon_size = 64,
        stack_size = 100,
        weight = 2 * kg,
    },
})
